// Sidebar is generated from the docs/ directory tree: each folder is a
// section (labelled by its _category_.json) and each file's position comes
// from its sidebar_position frontmatter.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};
module.exports = sidebars;
