#!/usr/bin/env node
/**
 * Build docs/aire/revise.md — every AIRE architecture diagram on one page,
 * in sidebar order, for pre-interview revision.
 *
 * Generated rather than hand-written so it cannot drift from the actual
 * pages and rendered diagrams. Re-run after adding a design.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const AIRE = path.join(ROOT, 'docs/aire');
const SVG = path.join(ROOT, 'static/diagrams');
const SKIP = new Set(['common-concepts', 'revise', 'infra-anthropic']);

const fm = (text, key) => {
  const m = text.match(new RegExp(`^${key}:\\s*"?(.*?)"?\\s*$`, 'm'));
  return m ? m[1] : '';
};

const pages = fs
  .readdirSync(AIRE)
  .filter((f) => f.endsWith('.md'))
  .map((f) => {
    const slug = f.replace(/\.md$/, '');
    const text = fs.readFileSync(path.join(AIRE, f), 'utf8');
    return {
      slug,
      title: fm(text, 'title'),
      desc: fm(text, 'description'),
      pos: parseFloat(fm(text, 'sidebar_position')) || 999,
      hasSvg: fs.existsSync(path.join(SVG, slug, 'architecture.svg')),
    };
  })
  .filter((p) => !SKIP.has(p.slug) && p.hasSvg)
  .sort((a, b) => a.pos - b.pos);

// difficulty + tags live at the front of the description, separated by ·
const chips = (d) =>
  d
    .split('·')
    .map((s) => s.trim())
    .filter(Boolean)
    .slice(0, 5)
    .map((s) => `<span class="rv-chip">${s}</span>`)
    .join('');

const body = pages
  .map(
    (p) => `
## ${p.title} {#rv-${p.slug}}

<div class="rv-meta">${chips(p.desc)}<a class="rv-open" href="/docs/aire/${p.slug}">open the full page &rarr;</a></div>

<div class="rv-scroll">
<img src="/diagrams/${p.slug}/architecture.svg" alt="Architecture diagram for ${p.title}" class="rv-img" />
</div>
`
  )
  .join('\n');

const out = `---
title: "Revise: every architecture on one page"
slug: /aire/revise
sidebar_position: 2
sidebar_label: "Revise — every architecture"
description: "reference · all ${pages.length} AIRE architectures in one scroll · generated, do not edit by hand"
---

<!-- GENERATED BY scripts/gen-revise.js — do not edit by hand. Re-run the script. -->

## How to use this page

<header>
  
  <span class="tag">reference · all ${pages.length} AIRE architectures in one scroll · generated by scripts/gen-revise.js</span>
</header>

<p>Every architecture diagram in this section, in sidebar order, on one page. Built for the last hour before an interview: scroll it, and for each one try to say the requirements, the central trade-off and the failure mode <em>before</em> you look at the picture. Where a diagram is wider than the column, scroll it sideways — it renders at full size rather than shrinking to fit.</p>

<p>For the mechanisms behind all of them, see <a href="/docs/aire/common-concepts">common concepts</a>. This page is deliberately just names and pictures.</p>

${body}
`;

fs.writeFileSync(path.join(AIRE, 'revise.md'), out);
console.log(`wrote docs/aire/revise.md with ${pages.length} architectures`);
